# docker-compose example to be able to
# test easily this image or to give some
# config to copy/paste for an easier 
# integration in an application
version: "3.5"

services:
  shibboleth-sp:
    build: ./image/
    image: abesesr/docker-shibboleth-sp:1.0.0
    ports:
        - 443:443
    environment:
        # container parameters, values comming from .env
        # (see .env-dist example)
        - RENATER_SP_ENTITY_ID
        - RENATER_SP_ADMIN_MAIL
        - RENATER_SP_HTTPD_SERVER_NAME
        - RENATER_SP_HTTPD_LOG_LEVEL
        - RENATER_SP_HTTPD_PROTECTED_PATH
        - RENATER_SP_HTTPD_PUBLIC_PROXY_TO
        - RENATER_SP_HTTPD_PROTECTED_PROXY_TO
    restart: unless-stopped
